### PR TITLE
fallbacks.json: el->en

### PR DESCRIPTION
**Pull request by catrope**
Bug: [T193866](https://phabricator.wikimedia.org/T193866)

### CODE REVIEW

**Comment by nyurik** [comment]
Don't we always fallback to "en"?  I might have missed the change.  CC: @mooeypoo

**Comment by catrope** [comment]
No, that was changed. "en" is now skipped, we fall back straight to local. This is because there are so many places where `name:en` is defined but `name:$localLang` is not, and so English would win even if you're requesting the local language.

On the phab task, we told the requester that they should keep an eye out for places in Greece whose labels suddenly change from Greek to English after this change, and to be prepared to fix those in OSM.

**Comment by nyurik** [comment]
@catrope thx for the explanation, makes perfect sense.  I just hope we can start using `default_language` to determine the language of the `name` tag. Community is actively discussing and configuring that tag around the globe, and I believe it is already usable at ~80% of the planet.  Disclosure: @pnorman feels it is not ready yet.

**Comment by nyurik** [comment]
P.S.  The good thing about the default_language is that it is optional -- if it is defined, `name` can be used as `name:xx`.  If it is not defined, the current algorithm can work as before.

**Pull request merged**
